server {
    listen 80;
    listen [::]:80;

    server_name www.clipromocoes.com.br clipromocoes.com.br;

    root /usr/share/nginx/html/cafe;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name www.softweaver.com.br softweaver.com.br;

    root /usr/share/nginx/html/softweaver;
    index index.html;

    # API do questionário (Python dentro do container)
    location /api/questionario/ {
        client_max_body_size 64k;
        proxy_pass http://127.0.0.1:8000;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}